#if UNITY_EDITOR
namespace AngelPanel.Editor
{
    public static class AP_CoreLoc
    {
        public static AP_LocProvider Build()
        {
            AP_LocProvider p = new AP_LocProvider("ap.core", 0);

            p.Add("AP_MP_WINDOW_TITLE", "AngelPanel Core", "AngelPanel Core", "AngelPanel Core", "AngelPanel Core");
            p.Add("AP_AP_LANGUAGE", "Language", "语言", "語言", "言語");
            p.Add("AP_AP_READY", "Ready", "就绪", "就緒", "Ready");
            p.Add("AP_AP_NOT_READY", "Not Ready", "未就绪", "未就緒", "Not Ready");
            p.Add("AP_AP_VALID", "Valid", "有效", "有效", "Valid");
            p.Add("AP_AP_INVALID", "Invalid", "无效", "無效", "Invalid");

            p.Add("AP_MP_SIDEBAR_CORE", "Core", "Core", "Core", "Core");
            p.Add("AP_MP_SIDEBAR_MODULES", "Installed Modules", "已安装模块", "已安裝模組", "導入済みモジュール");
            p.Add("AP_MP_SIDEBAR_INFO", "Info", "信息", "資訊", "Info");
            p.Add("AP_MP_INFO_PICKER", "Info", "信息", "資訊", "Info");
            p.Add("AP_MP_INFO_PICKER_NONE", "Open", "打开", "開啟", "Open");
            p.Add("AP_MP_EMPTY_MODULES", "No extra modules detected.", "未检测到额外模块。", "未偵測到額外模組。", "追加モジュールは見つかりません。");
            p.Add("AP_MP_TAB_HOME", "Home", "主页", "主頁", "Home");
            p.Add("AP_MP_TAB_ABOUT", "About", "关于", "關於", "About");
            p.Add("AP_MP_HOST_VERSION", AP_CoreInfo.HostVersionLabel, AP_CoreInfo.HostVersionLabel, AP_CoreInfo.HostVersionLabel, AP_CoreInfo.HostVersionLabel);
            p.Add("AP_Cfg_TAB", "AP Config", "AP 配置", "AP 設定", "AP Config");
            p.Add("AP_Cfg_TITLE", "AP Config", "AP 配置", "AP 設定", "AP Config");
            p.Add("AP_Cfg_HINT", "", "", "", "");
            p.Add("AP_Cfg_NAV_PLACEMENT", "Navigation Placement", "导航位置", "導覽位置", "Navigation Placement");
            p.Add("AP_Cfg_NAV_LEFT", "Left Sidebar", "左侧竖栏", "左側豎欄", "Left Sidebar");
            p.Add("AP_Cfg_NAV_RIGHT", "Right Sidebar", "右侧竖栏", "右側豎欄", "Right Sidebar");
            p.Add("AP_Cfg_NAV_TOP", "Top Bar", "顶部横栏", "頂部橫欄", "Top Bar");
            p.Add("AP_Cfg_NAV_BOTTOM", "Bottom Bar", "底部横栏", "底部橫欄", "Bottom Bar");
            p.Add("AP_Cfg_SCALE_MODE", "Shell Scaling", "界面缩放方式", "介面縮放方式", "Shell Scaling");
            p.Add("AP_Cfg_SCALE_ADAPTIVE", "Adaptive", "随窗口自适应", "隨視窗自適應", "Adaptive");
            p.Add("AP_Cfg_SCALE_FIXED", "Fixed", "保持字体与按钮大小", "保持字體與按鈕大小", "Fixed");
            p.Add("AP_Cfg_BUTTON_HEIGHT", "Default Button Height", "默认按钮高度", "預設按鈕高度", "Default Button Height");
            p.Add("AP_Cfg_FONT_SIZE", "Default Font Size", "默认字体大小", "預設字體大小", "Default Font Size");
            p.Add("AP_Cfg_NAV_WIDTH", "Sidebar Width", "侧栏宽度", "側欄寬度", "Sidebar Width");
            p.Add("AP_Cfg_OVERFLOW_MODE", "Navigation Overflow", "导航溢出模式", "導覽溢出模式", "Navigation Overflow");
            p.Add("AP_Cfg_OVERFLOW_COMPACT", "Adaptive Narrow Buttons", "自适应窄按钮", "自適應窄按鈕", "Adaptive Narrow Buttons");
            p.Add("AP_Cfg_OVERFLOW_SCROLL", "Scroll Strip", "滚动条模式", "捲動條模式", "Scroll Strip");
            p.Add("AP_Cfg_SCALE_NOTE", "", "", "", "");
            p.Add("AP_Cfg_LAYOUT_NOTE", "", "", "", "");
            p.Add("AP_Cfg_PREVIEW_TITLE", "Current Shell Profile", "当前界面配置", "目前介面配置", "Current Shell Profile");
            p.Add("AP_Cfg_PREVIEW_HINT", "", "", "", "");
            p.Add("AP_Cfg_INFO_NOTE", "", "", "", "");
            p.Add("AP_Cfg_STATUS_TITLE", "Host Status", "宿主状态", "宿主狀態", "Host Status");
            p.Add("AP_Cfg_STATUS_HINT", "", "", "", "");
            p.Add("AP_Cfg_INTEGRATION_TITLE", "Integration Status", "集成状态", "整合狀態", "Integration Status");
            p.Add("AP_Cfg_INTEGRATION_HINT", "", "", "", "");
            p.Add("AP_Cfg_INTEGRATION_LAST_SCAN", "Last Scan: ", "上次扫描：", "上次掃描：", "Last Scan: ");
            p.Add("AP_Cfg_INTEGRATION_NEVER", "Not scanned yet", "尚未扫描", "尚未掃描", "Not scanned yet");
            p.Add("AP_Cfg_INTEGRATION_REFRESH", "Refresh", "刷新检测", "重新偵測", "Refresh");
            p.Add("AP_Cfg_INTEGRATION_SCANNING", "Scanning loaded assemblies. Results will refresh when the scan finishes.", "正在扫描当前已加载程序集，完成后结果会自动刷新。", "正在掃描目前已載入的組件，完成後結果會自動更新。", "Scanning loaded assemblies. Results will refresh when the scan finishes.");
            p.Add("AP_Cfg_INTEGRATION_NOTE", "", "", "", "");
            p.Add("AP_Cfg_INT_STATE_READY", "Ready", "已检测到", "已偵測到", "Ready");
            p.Add("AP_Cfg_INT_STATE_MISSING", "Missing", "未检测到", "未偵測到", "Missing");
            p.Add("AP_Cfg_INT_VRCSDK", "VRCSDK Worlds", "VRCSDK Worlds", "VRCSDK Worlds", "VRCSDK Worlds");
            p.Add("AP_Cfg_INT_VRCSDK_NOTE", "", "", "", "");
            p.Add("AP_Cfg_INT_UDONSHARP", "UdonSharp", "UdonSharp", "UdonSharp", "UdonSharp");
            p.Add("AP_Cfg_INT_UDONSHARP_NOTE", "", "", "", "");
            p.Add("AP_Cfg_INT_BAKERY", "Bakery", "Bakery", "Bakery", "Bakery");
            p.Add("AP_Cfg_INT_BAKERY_NOTE", "", "", "", "");
            p.Add("AP_Cfg_INT_MLP", "Magic Light Probes", "Magic Light Probes", "Magic Light Probes", "Magic Light Probes");
            p.Add("AP_Cfg_INT_MLP_NOTE", "", "", "", "");
            p.Add("AP_Cfg_INT_VRCLV", "VRCLightVolumes", "VRCLightVolumes", "VRCLightVolumes", "VRCLightVolumes");
            p.Add("AP_Cfg_INT_VRCLV_NOTE", "", "", "", "");
            p.Add("AP_Cfg_INT_VRCLV_MANAGER", "VRCLV Manager", "VRCLV Manager", "VRCLV Manager", "VRCLV Manager");
            p.Add("AP_Cfg_INT_VRCLV_MANAGER_NOTE", "", "", "", "");
            p.Add("AP_MP_CONTENT_NOT_FOUND", "The selected page is not available.", "所选页面不可用。", "所選頁面不可用。", "選択したページは利用できません。");
            p.Add("AP_MP_LOC_PROVIDER_COUNT", "Loc Providers", "语言提供器", "語言提供器", "Loc Providers");
            p.Add("AP_MP_LOC_OVERLAY_STATUS", "Loc Overlay", "语言 Overlay", "語言 Overlay", "Loc Overlay");
            p.Add("AP_MP_LOC_OVERLAY_LOADED", "Loaded", "已加载", "已載入", "Loaded");
            p.Add("AP_MP_LOC_OVERLAY_NOT_LOADED", "Not Loaded", "未加载", "未載入", "Not Loaded");

            p.Add("AP_MP_MAIN_WORKSPACE_HEADER", "Workspace", "工作区", "工作區", "Workspace");
            p.Add("AP_MP_WORKSPACE_MODE", "Mode", "模式", "模式", "Mode");
            p.Add("AP_MP_WORKSPACE_MODE_SIMPLE", "Simple", "简洁", "簡潔", "Simple");
            p.Add("AP_MP_WORKSPACE_MODE_ADVANCED", "Advanced", "高级", "高級", "Advanced");
            p.Add("AP_MP_MAIN_WORKSPACE_HINT_SIMPLE", "", "", "", "");
            p.Add("AP_MP_MAIN_WORKSPACE_HINT_ADVANCED", "", "", "", "");
            p.Add("AP_MP_MAIN_WORKSPACE_ADVANCED_HINT", "", "", "", "");
            p.Add("AP_MP_POLYCOUNT_HEADER", "PolyCount", "面数统计", "面數統計", "PolyCount");
            p.Add("AP_MP_POLYCOUNT_WINDOW_TITLE", "PolyCount Workspace", "PolyCount 工作区", "PolyCount 工作區", "PolyCount Workspace");
            p.Add("AP_MP_POLYCOUNT_WINDOW_HINT_SIMPLE", "", "", "", "");
            p.Add("AP_MP_POLYCOUNT_WINDOW_HINT_ADVANCED", "", "", "", "");
            p.Add("AP_MP_POLYCOUNT_DETACHED_HINT", "", "", "", "");
            p.Add("AP_MP_OPEN_DETACHED_POLYCOUNT", "Open PolyCount Window", "打开 PolyCount 窗口", "打開 PolyCount 視窗", "Open PolyCount Window");
            p.Add("AP_MP_FOCUS_DETACHED_POLYCOUNT", "Focus PolyCount Window", "定位 PolyCount 窗口", "定位 PolyCount 視窗", "Focus PolyCount Window");
            p.Add("AP_MP_OPEN_HOST_PANEL", "Open Main Panel", "打开主面板", "打開主面板", "Open Main Panel");
            p.Add("AP_MP_MAIN_QUICKOPS_ONLY", "QuickOps Focus", "QuickOps 专注模式", "QuickOps 專注模式", "QuickOps Focus");
            p.Add("AP_MP_MAIN_QUICKOPS_ONLY_HINT", "", "", "", "");
            p.Add("AP_MP_SELECTION_HINT", "", "", "", "");
            p.Add("AP_MP_REFRESH_SELECTION", "Refresh Selection", "刷新选中", "刷新選取", "Refresh Selection");
            p.Add("AP_MP_REFRESH_TOTAL", "Refresh Total", "刷新总数", "刷新總數", "Refresh Total");
            p.Add("AP_MP_COUNT_SCENE", "Refresh Total", "刷新总数", "刷新總數", "Refresh Total");
            p.Add("AP_MP_COUNT_ACTIVE_ONLY", "Active Only", "仅激活物体", "僅啟用物件", "Active Only");
            p.Add("AP_MP_CLEAR_SCENE_CACHE", "Clear Cache", "清空缓存", "清空快取", "Clear Cache");
            p.Add("AP_MP_POLYCOUNT_CACHE_HEADER", "Scene Cache", "场景缓存", "場景快取", "Scene Cache");
            p.Add("AP_MP_SELECTED_TOTAL", "Selected", "选中", "選取", "Selected");
            p.Add("AP_MP_SCENE_TOTAL", "Scene Total", "场景总面数", "場景總面數", "Scene Total");
            p.Add("AP_MP_ACTIVE_TOTAL", "Active Total", "激活总面数", "啟用總面數", "Active Total");
            p.Add("AP_MP_LAST_REFRESH", "Last Refresh", "上次刷新", "上次刷新", "Last Refresh");
            p.Add("AP_MP_DIRTY", "Dirty", "已过期", "已過期", "Dirty");
            p.Add("AP_MP_CLEAN", "Clean", "已同步", "已同步", "Clean");
            p.Add("AP_MP_NO_SCENE_CACHE", "No Cache", "无缓存", "無快取", "No Cache");
            p.Add("AP_MP_WORKSPACE_STATUS_IDLE", "Idle", "空闲", "閒置", "Idle");
            p.Add("AP_MP_WORKSPACE_STATUS_DIRTY", "Cache needs refresh", "缓存需要刷新", "快取需要刷新", "Cache needs refresh");
            p.Add("AP_MP_WORKSPACE_STATUS_READY", "Ready", "已准备", "已準備", "Ready");
            p.Add("AP_MP_SIMPLE_STRIP_HINT", "", "", "", "");
            p.Add("AP_MP_TOTAL_MODE_MANUAL", "Manual Total", "手动总数", "手動總數", "Manual Total");
            p.Add("AP_MP_TOTAL_MODE_REALTIME", "Realtime Total", "实时总数", "即時總數", "Realtime Total");
            p.Add("AP_MP_TOTAL_INCLUDES_INACTIVE", "Includes inactive objects", "包含未激活物体", "包含未啟用物件", "Includes inactive objects");
            p.Add("AP_MP_TOTAL_EXCLUDES_INACTIVE", "Active objects only", "仅统计激活物体", "僅統計啟用物件", "Active objects only");
            p.Add("AP_MP_POLYCOUNT_SETTINGS_HEADER", "PolyCount Settings", "PolyCount 设置", "PolyCount 設定", "PolyCount Settings");
            p.Add("AP_MP_POLYCOUNT_SETTINGS_HINT", "", "", "", "");
            p.Add("AP_MP_SELECTED_FONT_SIZE", "Selected Size", "选中数字大小", "選取數字大小", "Selected Size");
            p.Add("AP_MP_TOTAL_FONT_SIZE", "Total Size", "总数字大小", "總數字大小", "Total Size");
            p.Add("AP_MP_SELECTED_BASE_COLOR", "Selected Base Color", "选中基础颜色", "選取基礎顏色", "Selected Base Color");
            p.Add("AP_MP_TOTAL_BASE_COLOR", "Total Base Color", "总数基础颜色", "總數基礎顏色", "Total Base Color");
            p.Add("AP_MP_SELECTED_THRESHOLD_SETTINGS", "Selected Thresholds", "选中阈值", "選取閾值", "Selected Thresholds");
            p.Add("AP_MP_TOTAL_THRESHOLD_SETTINGS", "Total Thresholds", "总数阈值", "總數閾值", "Total Thresholds");
            p.Add("AP_MP_SIMPLE_ANCHOR", "Simple Alignment", "Simple 对齐", "Simple 對齊", "Simple Alignment");
            p.Add("AP_MP_BASE_COLOR", "Base Color", "基础颜色", "基礎顏色", "Base Color");
            p.Add("AP_MP_TOTAL_INCLUDE_INACTIVE_TOGGLE", "Total includes inactive objects", "总面数包含未激活物体", "總面數包含未啟用物件", "Total includes inactive objects");
            p.Add("AP_MP_TOTAL_INCLUDE_DISABLED_RENDERER_TOGGLE", "Total includes disabled renderers", "总面数包含已禁用 Renderer", "總面數包含已停用 Renderer", "Total includes disabled renderers");
            p.Add("AP_MP_REALTIME_TOTAL_TOGGLE", "Enable realtime total counting", "启用实时总面数统计", "啟用即時總面數統計", "Enable realtime total counting");
            p.Add("AP_MP_REALTIME_INTERVAL", "Realtime Interval (Seconds)", "实时统计间隔（秒）", "即時統計間隔（秒）", "Realtime Interval (Seconds)");
            p.Add("AP_MP_REALTIME_WARNING", "Short realtime intervals can cause editor stutter on heavy scenes.", "实时统计频率过短可能导致编辑器卡顿。", "即時統計頻率過短可能導致編輯器卡頓。", "Short realtime intervals can cause editor stutter on heavy scenes.");
            p.Add("AP_MP_THRESHOLD_SETTINGS", "Color Thresholds", "颜色阈值", "顏色閾值", "Color Thresholds");
            p.Add("AP_MP_THRESHOLD_ADD", "Add Threshold", "添加阈值", "新增閾值", "Add Threshold");
            p.Add("AP_MP_THRESHOLD_VALUE", "Value", "阈值", "閾值", "Value");
            p.Add("AP_MP_THRESHOLD_COLOR", "Color", "颜色", "顏色", "Color");

            p.Add("AP_AB_WELCOME_TITLE", "Welcome to AngelPanel Core", "欢迎使用 AngelPanel Core", "歡迎使用 AngelPanel Core", "Welcome to AngelPanel Core");
            p.Add("AP_AB_WELCOME_BODY", "AP Core is the free host shell. Keep it clean, then grow it with modules later.", "AP Core 是免费的宿主外壳。先保持干净，再按需扩展模块。", "AP Core 是免費的宿主外殼。先保持乾淨，再按需擴展模組。", "AP Core is the free host shell. Keep it clean, then grow it with modules later.");
            p.Add("AP_AB_WELCOME_NOTE", "", "", "", "");
            p.Add("AP_AB_WELCOME_CONTINUE", "Enter Core", "进入 Core", "進入 Core", "Enter Core");
            p.Add("AP_AB_TITLE", "About / DLC Status", "关于 / DLC 状态", "關於 / DLC 狀態", "About / DLC Status");
            p.Add("AP_AB_HINT", "", "", "", "");
            p.Add("AP_AB_OVERVIEW_TITLE", "Core Identity", "Core 门面", "Core 門面", "Core Identity");
            p.Add("AP_AB_PRODUCT_SUMMARY", "Product Summary", "产品概览", "產品概覽", "Product Summary");
            p.Add("AP_AB_PRODUCT_SUMMARY_NOTE", "", "", "", "");
            p.Add("AP_AB_POSITIONING_NOTE", "", "", "", "");
            p.Add("AP_AB_AUTHOR", "Author", "作者", "作者", "Author");
            p.Add("AP_AB_VERSION", "Version", "版本", "版本", "Version");
            p.Add("AP_AB_COMMUNITY", "Community", "社区", "社群", "Community");
            p.Add("AP_AB_STORE", "Store", "商店", "商店", "Store");
            p.Add("AP_AB_SUPPORT", "Support", "支持", "支持", "Support");
            p.Add("AP_AB_INSTALLED_MODULES", "Installed Modules", "已安装模块", "已安裝模組", "Installed Modules");
            p.Add("AP_AB_CORE_COMPONENTS", "Core Components", "核心组件", "核心組件", "Core Components");
            p.Add("AP_AB_CONNECTED_TOOLS", "Connected Tools", "已接入工具", "已接入工具", "Connected Tools");
            p.Add("AP_AB_BADGE_CORE", "CORE", "核心", "核心", "CORE");
            p.Add("AP_AB_MISSING_MODULES", "Missing / Suggested Modules", "缺失 / 推荐模块", "缺少 / 推薦模組", "Missing / Suggested Modules");
            p.Add("AP_AB_CAPABILITIES", "Capabilities", "能力注册", "能力註冊", "Capabilities");
            p.Add("AP_AB_PATHS", "Paths", "路径", "路徑", "Paths");
            p.Add("AP_AB_INSTALLED_HINT", "", "", "", "");
            p.Add("AP_AB_MISSING_HINT", "", "", "", "");
            p.Add("AP_AB_CAPABILITY_HINT", "", "", "", "");
            p.Add("AP_AB_PATHS_HINT", "", "", "", "");
            p.Add("AP_AB_INSTALLED_NONE", "No registered modules yet.", "当前还没有注册模块。", "目前還沒有註冊模組。", "No registered modules yet.");
            p.Add("AP_AB_MISSING_NONE", "No suggested modules left.", "没有剩余推荐模块。", "沒有剩餘推薦模組。", "No suggested modules left.");
            p.Add("AP_AB_REVEAL_ASSET_ROOT", "Reveal Asset Root", "打开 Asset Root", "打開 Asset Root", "Reveal Asset Root");
            p.Add("AP_AB_REVEAL_CONFIG_ROOT", "Reveal Config Root", "打开 Config Root", "打開 Config Root", "Reveal Config Root");
            p.Add("AP_AB_ASSET_ROOT", "Asset Root", "资源根路径", "資源根路徑", "Asset Root");
            p.Add("AP_AB_APPDATA_ROOT", "AppData Root", "AppData 根路径", "AppData 根路徑", "AppData Root");
            p.Add("AP_AB_CONFIG_ROOT", "Config Root", "Config 根路径", "Config 根路徑", "Config Root");
            p.Add("AP_AB_LOC_ROOT", "Loc Root", "语言根路径", "語言根路徑", "Loc Root");
            p.Add("AP_AB_LOC_OVERLAY", "Loc Overlay", "语言 Overlay", "語言 Overlay", "Loc Overlay");
            p.Add("AP_AB_PROVIDER_COUNT", "Provider Count", "提供器数量", "提供器數量", "Provider Count");
            p.Add("AP_AB_SHOW_DETAILS", "Show details", "显示详情", "顯示詳情", "Show details");
            p.Add("AP_AB_OPEN_PRODUCT_PAGE", "Open Product Page", "打开商品页", "打開商品頁", "Open Product Page");
            p.Add("AP_AB_STATUS", "Status", "状态", "狀態", "Status");
            p.Add("AP_AB_STATUS_UNRELEASED", "Unreleased", "未发布", "未發布", "Unreleased");
            p.Add("AP_AB_OPEN_GITHUB", "Open GitHub", "打开 GitHub", "打開 GitHub", "Open GitHub");
            p.Add("AP_AB_OPEN_VPM_REPO", "Open VPM Repo", "打开 VPM 仓库", "打開 VPM 倉庫", "Open VPM Repo");
            p.Add("AP_AB_OPEN_BOOTH", "Open Booth", "打开 Booth", "打開 Booth", "Open Booth");
            p.Add("AP_AB_OPEN_WINDOW", "Open Window", "打开窗口", "打開視窗", "Open Window");
            p.Add("AP_AB_MODULE_ID", "Module ID", "模块 ID", "模組 ID", "Module ID");
            p.Add("AP_AB_STATUS", "Status", "状态", "狀態", "Status");
            p.Add("AP_AB_CAPABILITY_LABEL", "Capabilities", "能力项", "能力項", "Capabilities");
            p.Add("AP_AB_CAPABILITY_SHORT", "caps", "项能力", "項能力", "caps");
            p.Add("AP_AB_CAPABILITY_NONE", "No capabilities registered.", "当前没有注册能力。", "目前沒有註冊能力。", "No capabilities registered.");
            p.Add("AP_AB_BRAND_NOTE", "", "", "", "");
            p.Add("AP_AB_COMMUNITY_VALUE", "2d Angel", "2d Angel", "2d Angel", "2d Angel");
            p.Add("AP_AB_STORE_VALUE", "2d Angel VRC", "2d Angel VRC", "2d Angel VRC", "2d Angel VRC");
            p.Add("AP_AB_SUPPORT_VALUE", "Made by E-Mommy under 2d Angel.", "由 E-Mommy 制作，隶属 2d Angel。", "由 E-Mommy 製作，隸屬 2d Angel。", "Made by E-Mommy under 2d Angel.");
            p.Add("AP_AB_INSTALLED_COUNT", "Installed", "已安装", "已安裝", "Installed");
            p.Add("AP_AB_MISSING_COUNT", "Missing", "缺失", "缺少", "Missing");
            p.Add("AP_AB_SUMMARY_FREE", "Free Modules", "免费模块", "免費模組", "Free Modules");
            p.Add("AP_AB_SUMMARY_PAID", "Paid Products", "付费产品", "付費產品", "Paid Products");
            p.Add("AP_AB_SUMMARY_STANDALONE", "Standalone", "独立产品", "獨立產品", "Standalone");
            p.Add("AP_AB_PRODUCT_TARGET", "Target", "归位", "歸位", "Target");
            p.Add("AP_AB_BADGE_FREE", "FREE", "免费", "免費", "FREE");
            p.Add("AP_AB_BADGE_PRO", "PRO", "专业", "專業", "PRO");
            p.Add("AP_AB_BADGE_PAID", "PAID", "付费", "付費", "PAID");
            p.Add("AP_AB_BADGE_STANDALONE", "STANDALONE", "独立", "獨立", "STANDALONE");
            p.Add("AP_AB_LINE_FREE_MODULES", "Free Modules", "免费模块", "免費模組", "Free Modules");
            p.Add("AP_AB_LINE_PAID_PRODUCTS", "Paid Products", "付费产品", "付費產品", "Paid Products");
            p.Add("AP_AB_LINE_STANDALONE_PRODUCTS", "Standalone Products", "独立产品", "獨立產品", "Standalone Products");
            p.Add("AP_AB_TARGET_TOOLS", "Tools", "工具区", "工具區", "Tools");
            p.Add("AP_AB_TARGET_LIGHTING", "Lighting", "光照产品线", "光照產品線", "Lighting");
            p.Add("AP_AB_TARGET_RUNTIME", "Runtime", "运行时产品线", "執行時產品線", "Runtime");
            p.Add("AP_AB_TARGET_OPTIMIZING", "Optimizing", "优化产品线", "優化產品線", "Optimizing");
            p.Add("AP_AB_TARGET_STANDALONE", "Standalone", "独立发布", "獨立發佈", "Standalone");
            p.Add("AP_AB_PROD_PROBETOOLS_NAME", "ProbeTools Free", "ProbeTools 免费版", "ProbeTools 免費版", "ProbeTools Free");
            p.Add("AP_AB_PROD_PROBETOOLS_DESC", "Selection-driven probe scaffolding with Reflection Probe, LPG, MLP, LV Volume, Box Trigger Collider, and bounds expansion.", "基于选区的 Probe 脚手架工具，保留 Reflection Probe、LPG、MLP、LV Volume、Box Trigger Collider 和区域外扩。", "基於選取區的 Probe 腳手架工具，保留 Reflection Probe、LPG、MLP、LV Volume、Box Trigger Collider 與區域外擴。", "Selection-driven probe scaffolding with Reflection Probe, LPG, MLP, LV Volume, Box Trigger Collider, and bounds expansion.");
            p.Add("AP_AB_PROD_APK_FREE_NAME", "APK Free", "APK 免费版", "APK 免費版", "APK Free");
            p.Add("AP_AB_PROD_APK_FREE_DESC", "Standalone free keybinding module that can register into AP when installed.", "独立发布的免费快捷键模块，安装后可接入 AP。", "獨立發佈的免費快捷鍵模組，安裝後可接入 AP。", "Standalone free keybinding module that can register into AP when installed.");
            p.Add("AP_AB_PROD_LIGHTINGTOOLS_NAME", "AP Lighting Tools", "AP Lighting Tools", "AP Lighting Tools", "AP Lighting Tools");
            p.Add("AP_AB_PROD_LIGHTINGTOOLS_DESC", "Paid lighting workflow suite built around VRCLV, LPG, and Bakery-side production tools.", "付费光照工作流套件，围绕 VRCLV、LPG 和 Bakery 生产工具展开。", "付費光照工作流套件，圍繞 VRCLV、LPG 與 Bakery 生產工具展開。", "Paid lighting workflow suite built around VRCLV, LPG, and Bakery-side production tools.");
            p.Add("AP_AB_PROD_ISOZONE_NAME", "APVS / ISO Zone", "APVS / ISO Zone", "APVS / ISO Zone", "APVS / ISO Zone");
            p.Add("AP_AB_PROD_ISOZONE_DESC", "Paid spatial voice controller product for room-side isolation and zone-based voice shaping.", "付费空间语音控制产品，负责房间侧隔离和区域语音塑形。", "付費空間語音控制產品，負責房間側隔離與區域語音塑形。", "Paid spatial voice controller product for room-side isolation and zone-based voice shaping.");
            p.Add("AP_AB_PROD_AREATOOLS_NAME", "Area Tools", "Area Tools", "Area Tools", "Area Tools");
            p.Add("AP_AB_PROD_AREATOOLS_DESC", "Paid area-authoring toolkit for region logic, switches, bake grouping, and future zone behaviors.", "付费区域制作工具箱，用于区域逻辑、开关、烘焙分组以及后续区域行为。", "付費區域製作工具箱，用於區域邏輯、開關、烘焙分組以及後續區域行為。", "Paid area-authoring toolkit for region logic, switches, bake grouping, and future zone behaviors.");
            p.Add("AP_AB_PROD_LOCKSYSTEM_NAME", "LockSystem", "LockSystem", "LockSystem", "LockSystem");
            p.Add("AP_AB_PROD_LOCKSYSTEM_DESC", "Paid runtime interaction product for lock states, ownership flow, and grouped world controls.", "付费运行时交互产品，用于锁定状态、所有权流转和成组世界控制。", "付費執行時互動產品，用於鎖定狀態、所有權流轉與成組世界控制。", "Paid runtime interaction product for lock states, ownership flow, and grouped world controls.");
            p.Add("AP_AB_PROD_APK_PRO_NAME", "APK Pro", "APK Pro", "APK Pro", "APK Pro");
            p.Add("AP_AB_PROD_APK_PRO_DESC", "Paid advanced keybinding product with richer command routing, profiles, and expandable action maps.", "付费高级快捷键产品，提供更丰富的命令路由、配置档和可扩展动作映射。", "付費高級快捷鍵產品，提供更豐富的命令路由、設定檔與可擴展動作映射。", "Paid advanced keybinding product with richer command routing, profiles, and expandable action maps.");
            p.Add("AP_AB_PROD_TERRAINOPT_NAME", "Terrain Optimizer", "Terrain Optimizer", "Terrain Optimizer", "Terrain Optimizer");
            p.Add("AP_AB_PROD_TERRAINOPT_DESC", "Paid terrain optimization product for large world cleanup, simplification, and upload-side preparation.", "付费地形优化产品，面向大型地图清理、简化和上传前准备。", "付費地形優化產品，面向大型地圖清理、簡化與上傳前準備。", "Paid terrain optimization product for large world cleanup, simplification, and upload-side preparation.");
            p.Add("AP_AB_PROD_POINTCLOUD_NAME", "Point Cloud System", "点阵云系统", "點陣雲系統", "Point Cloud System");
            p.Add("AP_AB_PROD_POINTCLOUD_DESC", "Paid point-cloud product line for stylized world presentation and future water-audio linked workflows.", "付费点阵云产品线，面向风格化世界表现和后续与 Water Audio 关联的工作流。", "付費點陣雲產品線，面向風格化世界表現與後續和 Water Audio 關聯的工作流。", "Paid point-cloud product line for stylized world presentation and future water-audio linked workflows.");
            p.Add("AP_AB_PROD_HIERARCHY_NAME", "Hierarchy Tools", "Hierarchy Tools", "Hierarchy Tools", "Hierarchy Tools");
            p.Add("AP_AB_PROD_HIERARCHY_DESC", "Standalone scene organization product centered on world settings scaffolding and structured hierarchy cleanup.", "独立场景整理产品，围绕 World Settings 脚手架和层级结构清理展开。", "獨立場景整理產品，圍繞 World Settings 腳手架與層級結構清理展開。", "Standalone scene organization product centered on world settings scaffolding and structured hierarchy cleanup.");


            p.Add("AP_MP_SIDEBAR_OPTIMIZING", "Optimizing", "优化", "優化", "Optimizing");
            p.Add("AP_MP_SIDEBAR_TOOLS", "Tools", "工具", "工具", "Tools");
            p.Add("AP_Opt_TAB_DEBUG", "Debug", "调试", "調試", "Debug");
            p.Add("AP_DBG_PAGE_TITLE", "Scene Debug / Audit", "场景审计", "場景稽核", "Scene Debug / Audit");
            p.Add("AP_DBG_PAGE_HINT", "", "", "", "");
            p.Add("AP_DBG_TAB_BASIC", "Basic Scan", "基础扫描", "基礎掃描", "Basic Scan");
            p.Add("AP_DBG_TAB_LIGHTING", "Lighting", "Lighting", "Lighting", "Lighting");
            p.Add("AP_DBG_TAB_ONECLICK", "One Click", "一键", "一鍵", "One Click");
            p.Add("AP_DBG_COMING_SOON", "This section is reserved for the next migration pass.", "这部分留给下一轮迁移。", "這部分留給下一輪遷移。", "This section is reserved for the next migration pass.");
            p.Add("AP_DBG_HEADER", "Basic Scan", "基础扫描", "基礎掃描", "Basic Scan");
            p.Add("AP_DBG_INTRO", "Scan the current scene, current selection, or a manual root to get renderer counts, missing references, Udon-related objects, and shader buckets.", "扫描当前场景、当前选中或手动根节点，获取 Renderer 数量、缺失引用、Udon 相关物体和 Shader 分桶。", "掃描目前場景、目前選取或手動根節點，取得 Renderer 數量、缺失引用、Udon 相關物件與 Shader 分桶。", "Scan the current scene, current selection, or a manual root to get renderer counts, missing references, Udon-related objects, and shader buckets.");
            p.Add("AP_DBG_SCOPE", "Scope", "范围", "範圍", "Scope");
            p.Add("AP_DBG_SCOPE_SCENE", "Scene", "场景", "場景", "Scene");
            p.Add("AP_DBG_SCOPE_SELECTION", "Selection", "选中", "選取", "Selection");
            p.Add("AP_DBG_SCOPE_MANUAL", "Manual Root", "手动根节点", "手動根節點", "Manual Root");
            p.Add("AP_DBG_MANUAL_ROOT", "Manual Root", "手动根节点", "手動根節點", "Manual Root");
            p.Add("AP_DBG_SELECTION_HINT", "", "", "", "");
            p.Add("AP_DBG_SCAN", "Scan", "开始扫描", "開始掃描", "Scan");
            p.Add("AP_DBG_INCLUDE_INACTIVE", "Include Inactive", "包含未激活物体", "包含未啟用物件", "Include Inactive");
            p.Add("AP_DBG_WAITING", "Run a scan to fill this page with scene diagnostics.", "先执行一次扫描，这一页才会填入场景诊断结果。", "先執行一次掃描，這一頁才會填入場景診斷結果。", "Run a scan to fill this page with scene diagnostics.");
            p.Add("AP_DBG_NOTHING_TO_SCAN", "There is nothing to scan in the current scope.", "当前范围内没有可扫描内容。", "目前範圍內沒有可掃描內容。", "There is nothing to scan in the current scope.");
            p.Add("AP_DBG_OK", "OK", "确定", "確定", "OK");
            p.Add("AP_DBG_NO_VRC_TYPES", "VRC or Udon component types were not found. Renderer and shader data is still valid.", "未找到 VRC 或 Udon 组件类型，但 Renderer 与 Shader 数据仍然有效。", "未找到 VRC 或 Udon 元件型別，但 Renderer 與 Shader 資料仍然有效。", "VRC or Udon component types were not found. Renderer and shader data is still valid.");
            p.Add("AP_DBG_MISSING_SCRIPTS", "Missing Scripts", "缺失脚本", "缺失腳本", "Missing Scripts");
            p.Add("AP_DBG_SELECT_MISSING_SCRIPTS", "Select Missing Script Objects", "选中缺失脚本物体", "選取缺失腳本物件", "Select Missing Script Objects");
            p.Add("AP_DBG_MISSING_PREFABS", "Missing Prefab References", "缺失 Prefab 引用", "缺失 Prefab 引用", "Missing Prefab References");
            p.Add("AP_DBG_SELECT_MISSING_PREFABS", "Select Missing Prefab Objects", "选中缺失 Prefab 物体", "選取缺失 Prefab 物件", "Select Missing Prefab Objects");
            p.Add("AP_DBG_COUNTS_HEADER", "Scene Counts", "场景计数", "場景計數", "Scene Counts");
            p.Add("AP_DBG_RENDERERS", "Renderers", "Renderers", "Renderers", "Renderers");
            p.Add("AP_DBG_MATERIAL_SLOTS", "Material Slots", "材质槽位", "材質槽位", "Material Slots");
            p.Add("AP_DBG_UNIQUE_MATERIALS", "Unique Materials", "独立材质数", "獨立材質數", "Unique Materials");
            p.Add("AP_DBG_UDON", "UdonBehaviour", "UdonBehaviour", "UdonBehaviour", "UdonBehaviour");
            p.Add("AP_DBG_UDONSHARP", "UdonSharpBehaviour", "UdonSharpBehaviour", "UdonSharpBehaviour", "UdonSharpBehaviour");
            p.Add("AP_DBG_PICKUP", "VRCPickup", "VRCPickup", "VRCPickup", "VRCPickup");
            p.Add("AP_DBG_OBJECTSYNC", "VRCObjectSync", "VRCObjectSync", "VRCObjectSync", "VRCObjectSync");
            p.Add("AP_DBG_SELECT_UDON", "Select Udon Objects", "选中 Udon 物体", "選取 Udon 物件", "Select Udon Objects");
            p.Add("AP_DBG_SELECT_UDONSHARP", "Select UdonSharp Objects", "选中 UdonSharp 物体", "選取 UdonSharp 物件", "Select UdonSharp Objects");
            p.Add("AP_DBG_SELECT_PICKUP", "Select Pickup Objects", "选中 Pickup 物体", "選取 Pickup 物件", "Select Pickup Objects");
            p.Add("AP_DBG_SELECT_OBJECTSYNC", "Select ObjectSync Objects", "选中 ObjectSync 物体", "選取 ObjectSync 物件", "Select ObjectSync Objects");
            p.Add("AP_DBG_SHADERS_HEADER", "Shader Buckets", "Shader 分桶", "Shader 分桶", "Shader Buckets");
            p.Add("AP_DBG_FILTER", "Filter", "筛选", "篩選", "Filter");
            p.Add("AP_DBG_CLEAR", "Clear", "清空", "清空", "Clear");
            p.Add("AP_DBG_SHADER_NAME", "Shader", "Shader", "Shader", "Shader");
            p.Add("AP_DBG_COUNT", "Count", "数量", "數量", "Count");
            p.Add("AP_DBG_SELECT_OBJECTS", "Select Objects", "选中物体", "選取物件", "Select Objects");
            p.Add("AP_DBG_SELECT_MATERIALS", "Select Materials", "选中材质", "選取材質", "Select Materials");

            p.Add("AP_Opt_TAB_SHADER", "Shader", "着色器", "著色器", "Shader");
            p.Add("AP_Shd_PAGE_TITLE", "Shader", "Shader", "Shader", "Shader");
            p.Add("AP_Shd_PAGE_HINT", "", "", "", "");
            p.Add("AP_Shd_CARD_REPLACE_TITLE", "Shader Replace", "Shader 替换", "Shader 替換", "Shader Replace");
            p.Add("AP_Shd_CARD_REPLACE_HINT", "", "", "", "");
            p.Add("AP_Shd_SCOPE", "Scope", "范围", "範圍", "Scope");
            p.Add("AP_Shd_SCOPE_SCENE", "Scene", "场景", "場景", "Scene");
            p.Add("AP_Shd_SCOPE_SELECTION", "Selection", "选中", "選取", "Selection");
            p.Add("AP_Shd_SCOPE_BOTH", "Both", "两者", "兩者", "Both");
            p.Add("AP_Shd_TARGET", "Target Shader", "目标 Shader", "目標 Shader", "Target Shader");
            p.Add("AP_Shd_DRY_RUN", "Dry Run", "仅预演", "僅預演", "Dry Run");
            p.Add("AP_Shd_SCAN_STANDARD", "Scan Standard", "扫描 Standard", "掃描 Standard", "Scan Standard");
            p.Add("AP_Shd_CLEAR_RESULTS", "Clear Results", "清空结果", "清空結果", "Clear Results");
            p.Add("AP_Shd_RESULTS", "Results", "结果", "結果", "Results");
            p.Add("AP_Shd_RESULTS_NONE", "No scanned Standard materials yet.", "当前还没有扫描到 Standard 材质。", "目前還沒有掃描到 Standard 材質。", "まだ Standard マテリアルは検出されていません。");
            p.Add("AP_Shd_RESULTS_COUNT", "Standard Materials Found", "命中的 Standard 材质数", "命中的 Standard 材質數", "Standard Materials Found");
            p.Add("AP_Shd_USES", "Uses", "使用次数", "使用次數", "Uses");
            p.Add("AP_Shd_PING", "Ping", "定位", "定位", "Ping");
            p.Add("AP_Shd_SELECT_RESULTS", "Select Materials", "选中材质", "選取材質", "Select Materials");
            p.Add("AP_Shd_APPLY", "Apply Replace", "执行替换", "執行替換", "Apply Replace");
            p.Add("AP_Shd_TARGET_MISSING", "Please assign a target shader first.", "请先指定目标 Shader。", "請先指定目標 Shader。", "先に対象 Shader を指定してください。");
            p.Add("AP_Shd_NOTHING_SCANNED", "Nothing scanned yet.", "还没有扫描结果。", "還沒有掃描結果。", "まだ走査結果がありません。");
            p.Add("AP_Shd_DRYRUN_DONE", "Dry run complete. {0} material(s) would be changed.", "预演完成。预计会改动 {0} 个材质。", "預演完成。預計會改動 {0} 個材質。", "ドライラン完了。{0} 個のマテリアルが変更対象です。");
            p.Add("AP_Shd_APPLY_CONFIRM", "Replace {0} material(s) with the selected shader?", "要把 {0} 个材质替换成当前目标 Shader 吗？", "要把 {0} 個材質替換成目前目標 Shader 嗎？", "{0} 個のマテリアルを現在の Shader に置き換えますか？");
            p.Add("AP_Shd_APPLY_DONE", "Replace complete. Changed {0} material(s).", "替换完成。共改动 {0} 个材质。", "替換完成。共改動 {0} 個材質。", "置き換え完了。{0} 個のマテリアルを変更しました。");
            p.Add("AP_Shd_INSTALL_CARD_TITLE", "Shader Installers", "Shader 安装入口", "Shader 安裝入口", "Shader Installers");
            p.Add("AP_Shd_INSTALL_CARD_HINT", "", "", "", "");
            p.Add("AP_Shd_INSTALL_REFRESH", "Refresh Status", "刷新状态", "刷新狀態", "Refresh Status");
            p.Add("AP_Shd_INSTALL_STATUS_INSTALLED", "Installed", "已安装", "已安裝", "Installed");
            p.Add("AP_Shd_INSTALL_STATUS_MISSING", "Not Detected", "未检测到", "未偵測到", "Not Detected");
            p.Add("AP_Shd_INSTALL_UPM", "Add via UPM", "通过 UPM 安装", "透過 UPM 安裝", "Add via UPM");
            p.Add("AP_Shd_INSTALL_REPO", "Open Repo", "打开仓库", "打開倉庫", "Open Repo");
            p.Add("AP_Shd_INSTALL_GUIDE", "Open Guide", "打开说明", "打開說明", "Open Guide");
            p.Add("AP_Shd_INSTALL_VPM", "Open VPM Listing", "打开 VPM Listing", "打開 VPM Listing", "Open VPM Listing");
            p.Add("AP_Shd_INSTALL_COPY", "Copy URL", "复制链接", "複製連結", "Copy URL");
            p.Add("AP_Shd_INSTALL_UPM_HINT", "UPM Git URL", "UPM Git 链接", "UPM Git 連結", "UPM Git URL");
            p.Add("AP_Shd_INSTALL_VPM_HINT", "VPM Listing", "VPM Listing", "VPM Listing", "VPM Listing");
            p.Add("AP_Shd_INSTALL_BUSY", "Package Manager is busy. Wait for the current install request to finish first.", "Package Manager 正在忙，请先等当前安装请求结束。", "Package Manager 正在忙，請先等目前安裝要求結束。", "Package Manager が使用中です。現在の導入処理が終わるまで待ってください。");
            p.Add("AP_Shd_INSTALL_ADDING", "Adding {0}...", "正在添加 {0}...", "正在加入 {0}...", "{0} を追加中...");
            p.Add("AP_Shd_INSTALL_SUCCESS", "Installed {0}.", "{0} 安装完成。", "{0} 安裝完成。", "{0} の導入が完了しました。");
            p.Add("AP_Shd_INSTALL_FAIL", "UPM install failed for {0}. Open the official guide or listing instead.", "{0} 的 UPM 安装失败，请改用官方说明或 listing。", "{0} 的 UPM 安裝失敗，請改用官方說明或 listing。", "{0} の UPM 導入に失敗しました。公式ガイドまたは listing を開いてください。");
            p.Add("AP_Shd_INSTALL_URL_COPIED", "Copied: {0}", "已复制：{0}", "已複製：{0}", "Copied: {0}");
            p.Add("AP_Shd_VENDOR_POIYOMI", "Poiyomi", "Poiyomi", "Poiyomi", "Poiyomi");
            p.Add("AP_Shd_VENDOR_LILTOON", "lilToon", "lilToon", "lilToon", "lilToon");
            p.Add("AP_Shd_VENDOR_Z3Y", "z3y Shaders", "z3y Shaders", "z3y Shaders", "z3y Shaders");
            p.Add("AP_Shd_VENDOR_FILAMENTED", "Filamented", "Filamented", "Filamented", "Filamented");
            p.Add("AP_Shd_VENDOR_POIYOMI_HINT", "Poiyomi now recommends installing through its official VPM repository or install guide.", "Poiyomi 现在更推荐用官方 VPM 仓库或安装说明。", "Poiyomi 現在更推薦使用官方 VPM 倉庫或安裝說明。", "Poiyomi は現在、公式 VPM リポジトリまたは導入ガイドの利用を推奨しています。");
            p.Add("AP_Shd_VENDOR_LILTOON_HINT", "Official lilToon supports a direct UPM Git path, so this page can add it straight into the project.", "官方 lilToon 支持直接 UPM Git 路径，所以这里可以直接装进工程。", "官方 lilToon 支援直接 UPM Git 路徑，所以這裡可以直接裝進工程。", "公式 lilToon は UPM Git パスに対応しているため、このページから直接追加できます。");
            p.Add("AP_Shd_VENDOR_Z3Y_HINT", "z3y shaders are best installed through the official VPM listing, then managed from VCC.", "z3y shaders 更适合通过官方 VPM listing 安装，再在 VCC 里管理。", "z3y shaders 更適合透過官方 VPM listing 安裝，再在 VCC 中管理。", "z3y shaders は公式 VPM listing から導入し、VCC で管理するのが適しています。");
            p.Add("AP_Shd_VENDOR_FILAMENTED_HINT", "Filamented is still mainly a repo/manual install workflow, so this page keeps a direct repo shortcut ready.", "Filamented 目前主要还是仓库/手动导入工作流，所以这里保留仓库入口。", "Filamented 目前主要還是倉庫/手動導入工作流，所以這裡保留倉庫入口。", "Filamented は現在も主にリポジトリ/手動導入の流れなので、ここではリポジトリ入口を残しています。");


            p.Add("AP_Opt_TAB_OCCLUSION", "Occlusion", "遮挡", "遮擋", "Occlusion");
            p.Add("AP_Opt_TAB_OCCLUSION_ROOMS", "Occlusion Rooms", "遮挡房间", "遮擋房間", "Occlusion Rooms");
            p.Add("AP_OCC_PAGE_TITLE", "Occlusion", "遮挡", "遮擋", "Occlusion");
            p.Add("AP_OCC_PAGE_HINT", "", "", "", "");
            p.Add("AP_OCC_SUGGEST_TITLE", "Suggestions", "建议值", "建議值", "Suggestions");
            p.Add("AP_OCC_PROFILE", "Suggestion Profile", "建议方案", "建議方案", "Suggestion Profile");
            p.Add("AP_OCC_ANALYZE", "Analyze and Suggest", "分析并给出建议", "分析並給出建議", "Analyze and Suggest");
            p.Add("AP_OCC_COPY_REPORT", "Copy Report", "复制报告", "複製報告", "Copy Report");
            p.Add("AP_OCC_SMALLEST_OCCLUDER", "Smallest Occluder", "最小遮挡体", "最小遮擋體", "Smallest Occluder");
            p.Add("AP_OCC_SMALLEST_HOLE", "Smallest Hole", "最小孔洞", "最小孔洞", "Smallest Hole");
            p.Add("AP_OCC_BACKFACE", "Backface Threshold", "背面阈值", "背面閾值", "Backface Threshold");
            p.Add("AP_OCC_STATIC_TITLE", "Static Flags", "静态标记", "靜態標記", "Static Flags");
            p.Add("AP_OCC_SELECTION_ONLY", "Selection Only", "仅对选中生效", "僅對選取生效", "Selection Only");
            p.Add("AP_OCC_MARK_OCCLUDER", "Mark Occluder", "标记为 Occluder", "標記為 Occluder", "Mark Occluder");
            p.Add("AP_OCC_MARK_OCCLUDEE", "Mark Occludee", "标记为 Occludee", "標記為 Occludee", "Mark Occludee");
            p.Add("AP_OCC_CLEAR_FLAGS", "Clear Occlusion Flags", "清除遮挡标记", "清除遮擋標記", "Clear Occlusion Flags");
            p.Add("AP_OCC_AREAS_TITLE", "Occlusion Areas", "Occlusion Areas", "Occlusion Areas", "Occlusion Areas");
            p.Add("AP_OCC_EXPAND_PERCENT", "Bounds Expand %", "Bounds 外扩百分比", "Bounds 外擴百分比", "Bounds Expand %");
            p.Add("AP_OCC_CREATE_FROM_SELECTION", "Create from Selection", "根据选中创建", "根據選取建立", "Create from Selection");
            p.Add("AP_OCC_CLEAR_AREAS", "Clear All Areas", "清除全部 Areas", "清除全部 Areas", "Clear All Areas");
            p.Add("AP_OCC_BAKE_TITLE", "Bake", "Bake", "Bake", "Bake");
            p.Add("AP_OCC_OPEN_WINDOW", "Open Occlusion Window", "打开 Occlusion 窗口", "打開 Occlusion 視窗", "Open Occlusion Window");
            p.Add("AP_OCC_BAKE_BG", "Bake in Background", "后台开始 Bake", "背景開始 Bake", "Bake in Background");
            p.Add("AP_OCC_REPORT_EMPTY", "No suitable static samples were found. Safe defaults were restored.", "没有找到合适的静态样本，已恢复安全默认值。", "沒有找到合適的靜態樣本，已恢復安全預設值。", "適切な静的サンプルが見つからなかったため、安全な既定値に戻しました。");
            p.Add("AP_OCC_REPORT_TEMPLATE", "Analyzed static samples: {0} | Structural occluders: {1} | Profile: {2}", "已分析静态样本：{0} | 结构遮挡候选：{1} | 方案：{2}", "已分析靜態樣本：{0} | 結構遮擋候選：{1} | 方案：{2}", "解析した静的サンプル: {0} | 構造遮蔽候補: {1} | プロファイル: {2}");
            p.Add("AP_OCC_FLAG_RESULT", "{0} {1}\nChanged: {2}\nSkipped: {3}", "{0} {1}\n已改动：{2}\n已跳过：{3}", "{0} {1}\n已改動：{2}\n已跳過：{3}", "{0} {1}\n変更: {2}\nスキップ: {3}");
            p.Add("AP_OCC_ACTION_SET", "Set", "设置", "設定", "Set");
            p.Add("AP_OCC_ACTION_CLEAR", "Clear", "清除", "清除", "Clear");
            p.Add("AP_OCC_NEED_SELECTION", "Select one or more objects first.", "请先选中一个或多个物体。", "請先選取一個或多個物件。", "先に 1 つ以上のオブジェクトを選択してください。");
            p.Add("AP_OCC_NO_BOUNDS", "No renderer or collider bounds were found in the current selection.", "当前选中里没有可用的 Renderer 或 Collider Bounds。", "目前選取中沒有可用的 Renderer 或 Collider Bounds。", "現在の選択から Renderer または Collider の Bounds を取得できませんでした。");
            p.Add("AP_OCC_CLEAR_RESULT", "Removed {0} occlusion area object(s).", "已移除 {0} 个 Occlusion Area 物体。", "已移除 {0} 個 Occlusion Area 物件。", "{0} 個の Occlusion Area オブジェクトを削除しました。");
            p.Add("AP_OCC_WINDOW_FALLBACK", "The Occlusion window type was not found. Open it manually from Window > Rendering > Occlusion Culling.", "没找到 Occlusion 窗口类型，请手动从 Window > Rendering > Occlusion Culling 打开。", "找不到 Occlusion 視窗型別，請手動從 Window > Rendering > Occlusion Culling 開啟。", "Occlusion ウィンドウ型が見つかりません。Window > Rendering > Occlusion Culling から手動で開いてください。");
            p.Add("AP_OCC_BAKE_UNAVAILABLE", "Background bake is not available in this Unity version. Bake from the Occlusion window instead.", "当前 Unity 版本不支持后台 Bake，请改用 Occlusion 窗口手动执行。", "目前 Unity 版本不支援背景 Bake，請改用 Occlusion 視窗手動執行。", "この Unity バージョンではバックグラウンド Bake を利用できません。Occlusion ウィンドウから実行してください。");
            p.Add("AP_OCC_BAKE_STARTED", "Occlusion baking was started in the background. Check progress in the Occlusion window.", "已在后台启动 Occlusion Bake，请到 Occlusion 窗口查看进度。", "已在背景啟動 Occlusion Bake，請到 Occlusion 視窗查看進度。", "バックグラウンドで Occlusion Bake を開始しました。進行状況は Occlusion ウィンドウで確認してください。");
            p.Add("AP_OCC_BAKE_FAILED", "Failed to start background bake. Open the Occlusion window and bake manually.", "后台 Bake 启动失败，请打开 Occlusion 窗口手动执行。", "背景 Bake 啟動失敗，請開啟 Occlusion 視窗手動執行。", "バックグラウンド Bake の開始に失敗しました。Occlusion ウィンドウを開いて手動で実行してください。");

            p.Add("AP_OCCR_PAGE_TITLE", "Occlusion Rooms", "遮挡房间", "遮擋房間", "Occlusion Rooms");
            p.Add("AP_OCCR_PAGE_HINT", "Generate candidate occlusion view volumes from camera-occupiable interior space. This works best on indoor scenes with useful colliders.", "根据摄像机可活动的室内空间生成候选遮挡 View Volume，更适合有完整 Collider 的室内场景。", "根據攝影機可活動的室內空間生成候選遮擋 View Volume，更適合有完整 Collider 的室內場景。", "カメラが移動可能な屋内空間から候補となる遮蔽 View Volume を生成します。Collider が整った室内シーンで特に有効です。");
            p.Add("AP_OCCR_VOXEL", "Voxel Size", "体素尺寸", "體素尺寸", "Voxel Size");
            p.Add("AP_OCCR_CAMERA_SECTION", "Camera / Room Detection", "摄像机 / 房间检测", "攝影機 / 房間檢測", "Camera / Room Detection");
            p.Add("AP_OCCR_EYE_HEIGHT", "Eye Height", "视点高度", "視點高度", "Eye Height");
            p.Add("AP_OCCR_MIN_HEADROOM", "Min Headroom", "最小净空", "最小淨空", "Min Headroom");
            p.Add("AP_OCCR_MAX_CEILING", "Max Ceiling Search", "最大天花板搜索高度", "最大天花板搜尋高度", "Max Ceiling Search");
            p.Add("AP_OCCR_MIN_FLOOR_NORMAL", "Min Floor Normal Y", "地面法线最小 Y", "地面法線最小 Y", "Min Floor Normal Y");
            p.Add("AP_OCCR_REQUIRE_CEILING", "Require Ceiling (Indoor Bias)", "必须命中天花板（偏向室内）", "必須命中天花板（偏向室內）", "Require Ceiling (Indoor Bias)");
            p.Add("AP_OCCR_MERGE_SECTION", "Merge", "合并", "合併", "Merge");
            p.Add("AP_OCCR_FLOOR_TOLERANCE", "Floor Merge Tolerance", "地面合并容差", "地面合併容差", "Floor Merge Tolerance");
            p.Add("AP_OCCR_CEILING_TOLERANCE", "Ceiling Merge Tolerance", "天花板合并容差", "天花板合併容差", "Ceiling Merge Tolerance");
            p.Add("AP_OCCR_MIN_CELLS", "Min Cells Per Volume", "每个体积最少格数", "每個體積最少格數", "Min Cells Per Volume");
            p.Add("AP_OCCR_PADDING_XZ", "XZ Padding", "XZ 外扩", "XZ 外擴", "XZ Padding");
            p.Add("AP_OCCR_PADDING_Y", "Y Padding", "Y 外扩", "Y 外擴", "Y Padding");
            p.Add("AP_OCCR_GENERATE", "Generate Candidate Rooms", "生成候选房间", "生成候選房間", "Generate Candidate Rooms");
            p.Add("AP_OCCR_PROGRESS_TITLE", "Scanning Occupiable Space", "扫描可活动空间中", "掃描可活動空間中", "Scanning Occupiable Space");
            p.Add("AP_OCCR_PROGRESS_BODY", "Column {0}/{1}, {2}/{3}", "列 {0}/{1}，{2}/{3}", "欄 {0}/{1}，{2}/{3}", "列 {0}/{1}, {2}/{3}");
            p.Add("AP_OCCR_CANCELLED", "Room generation was cancelled.", "已取消房间生成。", "已取消房間生成。", "ルーム生成をキャンセルしました。");
            p.Add("AP_OCCR_NONE", "No camera-occupiable indoor cells were found. The scene may need better colliders or less strict filters.", "没有找到可供摄像机活动的室内格子，场景可能缺少合适的 Collider，或者当前筛选过严。", "沒有找到可供攝影機活動的室內格子，場景可能缺少合適的 Collider，或目前篩選過嚴。", "カメラが移動可能な屋内セルは見つかりませんでした。Collider が不足しているか、現在の条件が厳しすぎる可能性があります。");
            p.Add("AP_OCCR_DONE", "Detected floor cells: {0}\nCreated candidate view volumes: {1}", "检测到地面格子：{0}\n生成候选 View Volume：{1}", "檢測到地面格子：{0}\n生成候選 View Volume：{1}", "検出した床セル: {0}\n生成した候補 View Volume: {1}");

            p.Add("AP_DBG_TAB_EVENTS", "Event Audit", "高频事件", "高頻事件", "Event Audit");
            p.Add("AP_DBG_TAB_SCRIPT_ASSETS", "Script Assets", "脚本资源", "腳本資源", "Script Assets");
            p.Add("AP_DBG_EVT_PAGE_TITLE", "Runtime Event Audit", "运行时事件审计", "執行時事件稽核", "Runtime Event Audit");
            p.Add("AP_DBG_EVT_PAGE_HINT", "Scan scene or selection for hot callbacks that can quietly multiply per-frame cost, then jump straight to the objects or scripts using them.", "扫描场景或选中范围里的高频回调，找出那些会悄悄放大逐帧开销的脚本，然后直接定位到物体或脚本。", "掃描場景或選取範圍裡的高頻回呼，找出那些會悄悄放大逐幀開銷的腳本，然後直接定位到物件或腳本。", "シーンまたは選択範囲内の高頻度コールバックを走査し、フレーム負荷を静かに増幅させるスクリプトを洗い出します。");
            p.Add("AP_DBG_EVT_SCAN_SCOPE", "Scan Runtime Events", "扫描运行时事件", "掃描執行時事件", "Scan Runtime Events");
            p.Add("AP_DBG_EVT_RECOMMEND_TITLE", "Watch These First", "优先警惕这些", "優先警惕這些", "Watch These First");
            p.Add("AP_DBG_EVT_RECOMMEND_BODY", "Update, FixedUpdate, OnGUI, render callbacks, and audio callbacks can scale faster than you think when they show up across many objects.", "当这些回调分布在很多物体上时，Update、FixedUpdate、OnGUI、渲染回调和音频回调的成本会比想象中更快膨胀。", "當這些回呼分布在很多物件上時，Update、FixedUpdate、OnGUI、渲染回呼與音訊回呼的成本會比想像中更快膨脹。", "これらのコールバックが多数のオブジェクトに散らばると、Update、FixedUpdate、OnGUI、描画コールバック、音声コールバックの負荷は想像以上に膨らみます。");
            p.Add("AP_DBG_EVT_WAITING", "Run an event scan to fill this page with callback risk data.", "先执行一次事件扫描，这一页才会填入回调风险数据。", "先執行一次事件掃描，這一頁才會填入回呼風險資料。", "イベント走査を実行すると、このページにコールバックリスクのデータが表示されます。");
            p.Add("AP_DBG_EVT_SUMMARY", "Event Summary", "事件汇总", "事件彙總", "Event Summary");
            p.Add("AP_DBG_EVT_SCANNED_COMPONENTS", "MonoBehaviour Components", "MonoBehaviour 组件数", "MonoBehaviour 元件數", "MonoBehaviour Components");
            p.Add("AP_DBG_EVT_SCANNED_TYPES", "Script Types", "脚本类型数", "腳本型別數", "Script Types");
            p.Add("AP_DBG_EVT_TOTAL_HOTCALLS", "Matched Hot Callbacks", "命中的高频回调总数", "命中的高頻回呼總數", "Matched Hot Callbacks");
            p.Add("AP_DBG_EVT_OBJECTS", "Objects", "物体数", "物件數", "Objects");
            p.Add("AP_DBG_EVT_TYPES", "Types", "类型数", "型別數", "Types");
            p.Add("AP_DBG_EVT_SELECT_SCRIPTS", "Select Scripts", "选中脚本", "選取腳本", "Select Scripts");
            p.Add("AP_DBG_EVT_NONE", "No tracked hot callbacks were found in the current scope.", "当前范围内没有找到已跟踪的高频回调。", "目前範圍內沒有找到已追蹤的高頻回呼。", "現在の範囲で追跡対象の高頻度コールバックは見つかりませんでした。");
            p.Add("AP_DBG_SCRIPT_PAGE_TITLE", "Script Asset Audit", "脚本资源审计", "腳本資源稽核", "Script Asset Audit");
            p.Add("AP_DBG_SCRIPT_PAGE_HINT", "", "", "", "");
            p.Add("AP_DBG_SCRIPT_SCAN_SELECTED", "Scan Selected Scripts", "扫描所选脚本", "掃描所選腳本", "Scan Selected Scripts");
            p.Add("AP_DBG_SCRIPT_WAITING", "", "", "", "");
            p.Add("AP_DBG_SCRIPT_SELECTED_COUNT", "Selected Script Assets", "选中的脚本资源数", "選中的腳本資源數", "Selected Script Assets");
            p.Add("AP_DBG_PING_SCRIPT", "Ping Script", "定位脚本", "定位腳本", "Ping Script");
            p.Add("AP_DBG_SCRIPT_NONE", "No tracked hot callbacks were found in this script.", "这个脚本里没有找到已跟踪的高频回调。", "這個腳本裡沒有找到已追蹤的高頻回呼。", "このスクリプトには追跡対象の高頻度コールバックが見つかりませんでした。");
            p.Add("AP_DBG_RISK_HIGH", "High", "高风险", "高風險", "High");
            p.Add("AP_DBG_RISK_MEDIUM", "Medium", "中风险", "中風險", "Medium");
            p.Add("AP_DBG_EVT_UPDATE", "Update", "Update", "Update", "Update");
            p.Add("AP_DBG_EVT_LATEUPDATE", "LateUpdate", "LateUpdate", "LateUpdate", "LateUpdate");
            p.Add("AP_DBG_EVT_FIXEDUPDATE", "FixedUpdate", "FixedUpdate", "FixedUpdate", "FixedUpdate");
            p.Add("AP_DBG_EVT_ONGUI", "OnGUI", "OnGUI", "OnGUI", "OnGUI");
            p.Add("AP_DBG_EVT_ONWILLRENDEROBJECT", "OnWillRenderObject", "OnWillRenderObject", "OnWillRenderObject", "OnWillRenderObject");
            p.Add("AP_DBG_EVT_ONRENDEROBJECT", "OnRenderObject", "OnRenderObject", "OnRenderObject", "OnRenderObject");
            p.Add("AP_DBG_EVT_ONPRECULL", "OnPreCull", "OnPreCull", "OnPreCull", "OnPreCull");
            p.Add("AP_DBG_EVT_ONPRERENDER", "OnPreRender", "OnPreRender", "OnPreRender", "OnPreRender");
            p.Add("AP_DBG_EVT_ONPOSTRENDER", "OnPostRender", "OnPostRender", "OnPostRender", "OnPostRender");
            p.Add("AP_DBG_EVT_ONRENDERIMAGE", "OnRenderImage", "OnRenderImage", "OnRenderImage", "OnRenderImage");
            p.Add("AP_DBG_EVT_ONAUDIOFILTERREAD", "OnAudioFilterRead", "OnAudioFilterRead", "OnAudioFilterRead", "OnAudioFilterRead");
            p.Add("AP_DBG_EVT_ONANIMATORMOVE", "OnAnimatorMove", "OnAnimatorMove", "OnAnimatorMove", "OnAnimatorMove");
            p.Add("AP_DBG_EVT_ONANIMATORIK", "OnAnimatorIK", "OnAnimatorIK", "OnAnimatorIK", "OnAnimatorIK");
            p.Add("AP_DBG_HINT_UPDATE", "", "", "", "");
            p.Add("AP_DBG_HINT_LATEUPDATE", "", "", "", "");
            p.Add("AP_DBG_HINT_FIXEDUPDATE", "", "", "", "");
            p.Add("AP_DBG_HINT_ONGUI", "", "", "", "");
            p.Add("AP_DBG_HINT_ONWILLRENDEROBJECT", "", "", "", "");
            p.Add("AP_DBG_HINT_ONRENDEROBJECT", "", "", "", "");
            p.Add("AP_DBG_HINT_ONPRECULL", "", "", "", "");
            p.Add("AP_DBG_HINT_ONPRERENDER", "", "", "", "");
            p.Add("AP_DBG_HINT_ONPOSTRENDER", "", "", "", "");
            p.Add("AP_DBG_HINT_ONRENDERIMAGE", "", "", "", "");
            p.Add("AP_DBG_HINT_ONAUDIOFILTERREAD", "", "", "", "");
            p.Add("AP_DBG_HINT_ONANIMATORMOVE", "", "", "", "");
            p.Add("AP_DBG_HINT_ONANIMATORIK", "", "", "", "");

            return p;
        }
    }
}
#endif
