#if UNITY_EDITOR
using UnityEditor;

namespace AngelPanel.Editor
{
    public static class AP_ShaderLoc
    {
        private const string ProviderId = "ap.shader.page";

        [InitializeOnLoadMethod]
        private static void Register()
        {
            AP_LocProvider provider = new AP_LocProvider(ProviderId, 3200)
                .Add("AP_Shd_PAGE_TITLE", "Shader Tools", "Shader 工具", "Shader 工具")
                .Add("AP_Shd_PAGE_HINT", "", "", "")
                .Add("AP_Shd_CARD_REPLACE_TITLE", "Material Scan & Replace", "材质扫描与替换", "材質掃描與替換")
                .Add("AP_Shd_CARD_REPLACE_HINT", "", "", "")
                .Add("AP_Shd_SCOPE", "Scan Scope", "扫描范围", "掃描範圍")
                .Add("AP_Shd_SCOPE_SCENE", "Scene", "整个场景", "整個場景")
                .Add("AP_Shd_SCOPE_SELECTION", "Selection", "当前选中", "當前選中")
                .Add("AP_Shd_SCOPE_BOTH", "Both", "场景 + 选中", "場景 + 選中")
                .Add("AP_Shd_SOURCE_SHADER", "Source Shader Filter", "源 Shader 过滤", "來源 Shader 過濾")
                .Add("AP_Shd_TARGET", "Target Shader", "目标 Shader", "目標 Shader")
                .Add("AP_Shd_DRY_RUN", "Dry Run", "仅模拟执行", "僅模擬執行")
                .Add("AP_Shd_SCAN_ACTIONS", "Scan Actions", "扫描操作", "掃描操作")
                .Add("AP_Shd_SCAN_STANDARD", "Scan Standard", "扫描 Standard", "掃描 Standard")
                .Add("AP_Shd_SCAN_SELECTED_ALL", "Scan Selected Hierarchy", "扫描选中层级", "掃描選中層級")
                .Add("AP_Shd_SCAN_SELECTED_MATCHING", "Scan Selected Matching Source", "扫描选中层级中匹配源 Shader", "掃描選中層級中匹配來源 Shader")
                .Add("AP_Shd_CLEAR_RESULTS", "Clear", "清空结果", "清空結果")
                .Add("AP_Shd_SELECT_RESULTS", "Select Materials", "选中结果材质", "選中結果材質")
                .Add("AP_Shd_REPLACE_SELECTION_ACTIONS", "Direct Replace On Selection", "直接替换选中层级", "直接替換選中層級")
                .Add("AP_Shd_REPLACE_SELECTED_ALL", "Replace Selected Hierarchy", "替换选中层级", "替換選中層級")
                .Add("AP_Shd_REPLACE_SELECTED_MATCHING", "Replace Selected Matching Source", "替换选中层级中匹配源 Shader", "替換選中層級中匹配來源 Shader")
                .Add("AP_Shd_RESULTS", "Results", "结果列表", "結果列表")
                .Add("AP_Shd_RESULTS_COUNT", "Unique Materials", "唯一材质数", "唯一材質數")
                .Add("AP_Shd_RESULTS_NONE", "No materials are queued right now.", "当前没有排入结果集的材质。", "當前沒有排入結果集的材質。")
                .Add("AP_Shd_USES", "Uses", "使用次数", "使用次數")
                .Add("AP_Shd_PING", "Ping", "定位", "定位")
                .Add("AP_Shd_APPLY", "Apply To Current Results", "应用到当前结果", "套用到當前結果")
                .Add("AP_Shd_TARGET_MISSING", "Pick a target shader first.", "请先指定目标 Shader。", "請先指定目標 Shader。")
                .Add("AP_Shd_NOTHING_SCANNED", "Nothing has been scanned yet.", "目前还没有扫描结果。", "目前還沒有掃描結果。")
                .Add("AP_Shd_DRYRUN_DONE", "Dry Run complete. {0} material(s) are ready to be replaced.", "模拟执行完成，共有 {0} 个材质准备替换。", "模擬執行完成，共有 {0} 個材質準備替換。")
                .Add("AP_Shd_APPLY_CONFIRM", "Replace shaders on {0} material(s)?", "要替换这 {0} 个材质的 Shader 吗？", "要替換這 {0} 個材質的 Shader 嗎？")
                .Add("AP_Shd_APPLY_DONE", "Done. {0} material(s) changed.", "完成，已修改 {0} 个材质。", "完成，已修改 {0} 個材質。")
                .Add("AP_Shd_SHADER_UNKNOWN", "Unknown Shader", "未知 Shader", "未知 Shader")
                .Add("AP_Shd_SCAN_CONTEXT_STANDARD", "Scene/Scope Standard materials", "范围内的 Standard 材质", "範圍內的 Standard 材質")
                .Add("AP_Shd_SCAN_CONTEXT_SELECTION_ALL", "Selected objects and children", "选中物体及其子级", "選中物體及其子級")
                .Add("AP_Shd_SCAN_CONTEXT_SELECTION_FILTER", "Selected objects and children filtered by {0}", "选中物体及其子级，过滤 Shader：{0}", "選中物體及其子級，過濾 Shader：{0}")
                .Add("AP_Shd_SCAN_CONTEXT_FORMAT", "Current result set: {0} · {1} material(s)", "当前结果集：{0} · {1} 个材质", "當前結果集：{0} · {1} 個材質")
                .Add("AP_Shd_SELECTION_CARD_TITLE", "Selected Hierarchy Audit", "选中层级审查", "選中層級審查")
                .Add("AP_Shd_SELECTION_CARD_HINT", "", "", "")
                .Add("AP_Shd_SELECTION_REFRESH", "Refresh", "刷新", "重新整理")
                .Add("AP_Shd_SELECTION_ROOTS", "Selected Roots", "选中根物体", "選中根物體")
                .Add("AP_Shd_SELECTION_RENDERERS", "Renderers", "Renderer 数", "Renderer 數")
                .Add("AP_Shd_SELECTION_SLOTS", "Material Slots", "材质槽位", "材質槽位")
                .Add("AP_Shd_SELECTION_UNIQUE_MATERIALS", "Unique Materials", "唯一材质", "唯一材質")
                .Add("AP_Shd_SELECTION_UNIQUE_SHADERS", "Unique Shaders", "唯一 Shader", "唯一 Shader")
                .Add("AP_Shd_SELECTION_SHADER_LIST", "Shaders In Selection", "选中层级中的 Shader", "選中層級中的 Shader")
                .Add("AP_Shd_SELECTION_SHADER_LIST_EMPTY", "No shaders found in the current selection.", "当前选中层级中没有检测到 Shader。", "當前選中層級中沒有檢測到 Shader。")
                .Add("AP_Shd_INSTALL_CARD_TITLE", "Shader Library & Install Entry", "Shader 库与安装入口", "Shader 庫與安裝入口")
                .Add("AP_Shd_INSTALL_CARD_HINT", "", "", "")
                .Add("AP_Shd_INSTALL_PICKER", "Shader Library", "Shader 列表", "Shader 列表")
                .Add("AP_Shd_INSTALL_REFRESH", "Refresh Installed State", "刷新安装状态", "重新整理安裝狀態")
                .Add("AP_Shd_INSTALL_STATUS_INSTALLED", "Installed", "已安装", "已安裝")
                .Add("AP_Shd_INSTALL_STATUS_MISSING", "Missing", "未安装", "未安裝")
                .Add("AP_Shd_INSTALL_BUSY", "Another package install request is still running.", "已有一个安装请求正在进行中。", "已有一個安裝請求正在進行中。")
                .Add("AP_Shd_INSTALL_ADDING", "Installing {0}...", "正在安装 {0}...", "正在安裝 {0}...")
                .Add("AP_Shd_INSTALL_SUCCESS", "Install request finished: {0}", "安装请求完成：{0}", "安裝請求完成：{0}")
                .Add("AP_Shd_INSTALL_FAIL", "Install request failed: {0}", "安装请求失败：{0}", "安裝請求失敗：{0}")
                .Add("AP_Shd_INSTALL_REPO", "Repo", "仓库", "倉庫")
                .Add("AP_Shd_INSTALL_GUIDE", "Guide", "说明", "說明")
                .Add("AP_Shd_INSTALL_LISTING", "Listing", "Listing", "Listing")
                .Add("AP_Shd_INSTALL_UPM", "Install via UPM", "通过 UPM 安装", "透過 UPM 安裝")
                .Add("AP_Shd_INSTALL_STORE", "Store", "商店", "商店")
                .Add("AP_Shd_INSTALL_COPY_URL", "Copy Link", "复制链接", "複製連結")
                .Add("AP_Shd_INSTALL_URL_COPIED", "Copied: {0}", "已复制：{0}", "已複製：{0}")
                .Add("AP_Shd_SUPPORT_VRCLV", "VRCLV", "VRCLV", "VRCLV")
                .Add("AP_Shd_SUPPORT_MONOSH", "MonoSH", "MonoSH", "MonoSH")
                .Add("AP_Shd_SUPPORT_SHRNM", "SH/RNM", "SH/RNM", "SH/RNM")
                .Add("AP_Shd_SUPPORT_YES", "√", "√", "√")
                .Add("AP_Shd_SUPPORT_NO", "×", "×", "×")
                .Add("AP_Shd_SUPPORT_UNKNOWN", "?", "?", "?")
                .Add("AP_Shd_VENDOR_POIYOMI", "Poiyomi Toon Shader", "Poiyomi Toon Shader", "Poiyomi Toon Shader")
                .Add("AP_Shd_VENDOR_POIYOMI_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_POIYOMI_DESC", "Popular VRChat built-in toon shader. Good default choice when you want one large feature set and official package listing support.", "常见的 VRChat Built-in 卡通 Shader。想要一套大而全功能并且有官方包列表支持时，它是很稳的默认选项。", "常見的 VRChat Built-in 卡通 Shader。想要一套大而全功能並且有官方包列表支援時，它是很穩的預設選項。")
                .Add("AP_Shd_VENDOR_LILTOON", "lilToon", "lilToon", "lilToon")
                .Add("AP_Shd_VENDOR_LILTOON_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_LILTOON_DESC", "Very common Japanese shader pack in VRChat. Easy to recommend when you want a mature toon workflow and a straightforward Git install path.", "VRChat 圈里很常见的日系 Shader 包。想要成熟卡通工作流和直接 Git 安装时很适合推荐。", "VRChat 圈裡很常見的日系 Shader 包。想要成熟卡通工作流和直接 Git 安裝時很適合推薦。")
                .Add("AP_Shd_VENDOR_GRAPHLIT", "Graphlit / z3y", "Graphlit / z3y", "Graphlit / z3y")
                .Add("AP_Shd_VENDOR_GRAPHLIT_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_GRAPHLIT_DESC", "Strong choice when you want graph-based control or want to grow into more custom world-side lighting and material workflows.", "如果你想要图形化节点控制，或者准备往更自定义的世界侧材质和光照工作流发展，它很有价值。", "如果你想要圖形化節點控制，或者準備往更自訂的世界側材質和光照工作流發展，它很有價值。")
                .Add("AP_Shd_VENDOR_FILAMENTED", "Filamented", "Filamented", "Filamented")
                .Add("AP_Shd_VENDOR_FILAMENTED_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_FILAMENTED_DESC", "Great pick for world-side PBR. This entry is one of the few in the list with clearly documented MonoSH and SH/RNM support.", "很适合世界侧 PBR。这一项也是列表里少数明确写清了 MonoSH 与 SH/RNM 支持的 Shader。", "很適合世界側 PBR。這一項也是列表裡少數明確寫清了 MonoSH 與 SH/RNM 支援的 Shader。")
                .Add("AP_Shd_VENDOR_SCSS", "Silent Cel Shading Shader", "Silent Cel Shading Shader", "Silent Cel Shading Shader")
                .Add("AP_Shd_VENDOR_SCSS_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_SCSS_DESC", "Useful when you want a lighting-aware cel look instead of a flat fake-toon result.", "如果你想要的是会吃场景光照的赛璐璐风，而不是纯平假卡通，它很值得留意。", "如果你想要的是會吃場景光照的賽璐璐風，而不是純平假卡通，它很值得留意。")
                .Add("AP_Shd_VENDOR_MOCHIES", "Mochies Unity Shaders", "Mochies Unity Shaders", "Mochies Unity Shaders")
                .Add("AP_Shd_VENDOR_MOCHIES_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_MOCHIES_DESC", "Broad utility pack for worlds. Handy when one project needs several non-identical material types instead of only one core lit shader.", "很适合世界工程这种材质类型复杂的项目。一个工程里如果不只需要一种核心 Lit Shader，它会很顺手。", "很適合世界工程這種材質類型複雜的專案。一個工程裡如果不只需要一種核心 Lit Shader，它會很順手。")
                .Add("AP_Shd_VENDOR_ORELS", "Orels Unity Shaders", "Orels Unity Shaders", "Orels Unity Shaders")
                .Add("AP_Shd_VENDOR_ORELS_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_ORELS_DESC", "A practical world-side pack with an official VCC path. MonoSH support is commonly referenced around Bakery world workflows.", "偏务实的世界侧 Shader 包，而且有正式的 VCC 路径。它在 Bakery 世界工作流里也经常被提到用于 MonoSH。", "偏務實的世界側 Shader 包，而且有正式的 VCC 路徑。它在 Bakery 世界工作流裡也經常被提到用於 MonoSH。")
                .Add("AP_Shd_VENDOR_UNLITWF", "UnlitWF Shader Suite", "UnlitWF Shader Suite", "UnlitWF Shader Suite")
                .Add("AP_Shd_VENDOR_UNLITWF_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_UNLITWF_DESC", "A broad-purpose suite worth tracking if you want another long-running shader family in the VRChat ecosystem.", "如果你想在 VRChat 生态里多保留一个长期维护的 Shader 家族，它很值得纳入库里。", "如果你想在 VRChat 生態裡多保留一個長期維護的 Shader 家族，它很值得納入庫裡。")
                .Add("AP_Shd_VENDOR_ACLS", "ACLS Shader", "ACLS Shader", "ACLS Shader")
                .Add("AP_Shd_VENDOR_ACLS_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_ACLS_DESC", "Positioned around VRChat lighting realities. Useful to keep in the library as a stylized-but-world-aware alternative.", "它的定位本来就很贴近 VRChat 的光照现实，用来当作一种更风格化、但又考虑世界环境的选择很合适。", "它的定位本來就很貼近 VRChat 的光照現實，用來當作一種更風格化、但又考慮世界環境的選擇很合適。")
                .Add("AP_Shd_VENDOR_REALTOON", "RealToon", "RealToon", "RealToon")
                .Add("AP_Shd_VENDOR_REALTOON_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_REALTOON_DESC", "Useful to keep visible in the library even if you do not ship it by default, because some creators still rely on it for more authored anime looks.", "即使你不默认推广它，也建议放进库里，因为仍然有创作者会用它做更强调主观调教的动漫风效果。", "即使你不預設推廣它，也建議放進庫裡，因為仍然有創作者會用它做更強調主觀調教的動漫風效果。")
                .Add("AP_Shd_VENDOR_GENELIT", "GeneLit", "GeneLit", "GeneLit")
                .Add("AP_Shd_VENDOR_GENELIT_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_GENELIT_DESC", "Another PBR-leaning option for world materials when you want an alternative Standard-style base to compare against Filamented.", "如果你想要一个可和 Filamented 对照的 PBR 向 Standard 替代基底，它值得收进库里。", "如果你想要一個可和 Filamented 對照的 PBR 向 Standard 替代基底，它值得收進庫裡。")
                .Add("AP_Shd_VENDOR_USP", "Unity Shaders Plus", "Unity Shaders Plus", "Unity Shaders Plus")
                .Add("AP_Shd_VENDOR_USP_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_USP_DESC", "This is a useful migration-minded option because it stays close to Unity built-ins instead of reinventing the whole workflow.", "它很适合迁移思路，因为它不像大改工作流的 Shader 那样激进，而是更接近 Unity 原生路径。", "它很適合遷移思路，因為它不像大改工作流的 Shader 那樣激進，而是更接近 Unity 原生路徑。")
                .Add("AP_Shd_VENDOR_QUANTUM", "Quantum Shader", "Quantum Shader", "Quantum Shader")
                .Add("AP_Shd_VENDOR_QUANTUM_HINT", "", "", "")
                .Add("AP_Shd_VENDOR_QUANTUM_DESC", "Worth listing when you want a wider practical library instead of only the biggest names.", "如果你的目标是把这个库做成“实用大集合”，而不只是几个最大众名字，那它很值得纳入。", "如果你的目標是把這個庫做成「實用大集合」，而不只是幾個最大眾名字，那它很值得納入。")
                ;

            AP_Loc.RegisterProvider(provider);
        }
    }
}
#endif
